src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductsRepository::class)
 */
class Products
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Disponibilites::class, mappedBy="product_id", cascade={"persist", "remove"})
     */
    private $product_dispo;

    /**
     * @ORM\OneToMany(targetEntity=Bookings::class, mappedBy="product_id")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=OwnersContracts::class, mappedBy="product_id")
     */
    private $ownersContracts;

    /**
     * @ORM\ManyToOne(targetEntity=RentalsTypes::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $rental_type;

    /**
     * @ORM\ManyToOne(targetEntity=Owners::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner_id;

    /**
     * @ORM\OneToMany(targetEntity=RentalsPhotos::class, mappedBy="product_id")
     */
    private $photos;


    public function __construct()
    {
        $this->bookings = new ArrayCollection();
        $this->ownersContracts = new ArrayCollection();
        $this->photos = new ArrayCollection();
        $this->disponibilites = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRentalType(): ?RentalsTypes
    {
        return $this->rental_type;
    }

    public function setRentalType(RentalsTypes $rental_type): self
    {
        $this->rental_type = $rental_type;

        return $this;
    }

    public function getOwnerId(): ?Owners
    {
        return $this->owner_id;
    }

    public function setOwnerId(Owners $owner_id): self
    {
        $this->owner_id = $owner_id;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getProductDispo(): ?Disponibilites
    {
        return $this->product_dispo;
    }

    public function setProductDispo(Disponibilites $product_dispo): self
    {
        // set the owning side of the relation if necessary
        if ($product_dispo->getProductId() !== $this) {
            $product_dispo->setProductId($this);
        }

        $this->product_dispo = $product_dispo;

        return $this;
    }

    /**
     * @return Collection<int, Bookings>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Bookings $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setProductId($this);
        }

        return $this;
    }

    public function removeBooking(Bookings $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getProductId() === $this) {
                $booking->setProductId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, OwnersContracts>
     */
    public function getOwnersContracts(): Collection
    {
        return $this->ownersContracts;
    }

    public function addOwnersContract(OwnersContracts $ownersContract): self
    {
        if (!$this->ownersContracts->contains($ownersContract)) {
            $this->ownersContracts[] = $ownersContract;
            $ownersContract->setProductId($this);
        }

        return $this;
    }

    public function removeOwnersContract(OwnersContracts $ownersContract): self
    {
        if ($this->ownersContracts->removeElement($ownersContract)) {
            // set the owning side to null (unless already changed)
            if ($ownersContract->getProductId() === $this) {
                $ownersContract->setProductId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RentalsPhotos>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(RentalsPhotos $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setProductId($this);
        }

        return $this;
    }

    public function removePhoto(RentalsPhotos $photo): self
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getProductId() === $this) {
                $photo->setProductId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Disponibilites>
     */
    public function getDisponibilites(): Collection
    {
        return $this->disponibilites;
    }

    public function addDisponibilite(Disponibilites $disponibilite): self
    {
        if (!$this->disponibilites->contains($disponibilite)) {
            $this->disponibilites[] = $disponibilite;
            $disponibilite->setProductId($this);
        }

        return $this;
    }

    public function removeDisponibilite(Disponibilites $disponibilite): self
    {
        if ($this->disponibilites->removeElement($disponibilite)) {
            // set the owning side to null (unless already changed)
            if ($disponibilite->getProductId() === $this) {
                $disponibilite->setProductId(null);
            }
        }

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Owners;
use App\Entity\Products;
use App\Entity\RentalsTypes;
use App\Repository\OwnersRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('rental_type', EntityType::class, [
                'label' => 'Type de produit',
                'class' =>RentalsTypes::class,
                'placeholder' => 'Type de produit',
                'choice_label' => 'label',
                'expanded' => false,
                'multiple' => false,
                'mapped' => true
            ])
            ->add('label', TextType::class, [
                'label' => 'Titre',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Titre'
                ],
                'required' => true
            ])
            ->add('description', TextareaType::class, [

            ])
            ->add('owner_id', EntityType::class, [
                'label' => 'Propriétaire',
                'class' =>Owners::class,
                'placeholder' => 'Propriétaire',
                'choice_label' => 'lastname',
                'expanded' => false,
                'multiple' => false,
                'mapped' => true,
                'query_builder' => function(OwnersRepository $ownersRepo){
                    return $ownersRepo->findAllOrderedByLabel();
                },
            ])
            ->add('Enregistrer', SubmitType::class, [

            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Products::class,
        ]);
    }
}

src/Controller/ProductsController.php
<?php

namespace App\Controller;

use App\Entity\Disponibilites;
use App\Entity\Products;
use App\Form\ProductType;
use App\Repository\DisponibilitesRepository;
use App\Repository\ProductsRepository;
use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormTypeInterface;


class ProductsController extends AbstractController
{
    private ProductsRepository $productsRepo;
    private DisponibilitesRepository $dispoRepo;

    public function __construct(ProductsRepository $productsRepo, DisponibilitesRepository $dispoRepo)
    {
        $this->productsRepo = $productsRepo;
        $this->dispoRepo = $dispoRepo;
    }

    /**
     * Liste de tous les produits en accès public (mobile-home, emplacements et caravanes)
     * @Route("/housings", name="housings")
     */
    public function housings(): Response
    {
        $products = $this->productsRepo->findHousing();
        return $this->render('front/products.html.twig', [
            'products' => $products,
        ]);
    }

    /**
     * Liste de toutes les tentes en accès public
     * @return Response
     * @Route("/tentsites", name="tentsites")
     */
    public function tentSites(): Response
    {
        $products = $this->productsRepo->findTentSites();
        return $this->render('front/tentsites.html.twig', [
            'products' => $products,
        ]);
    }

    /**
     * Liste de tous les produits côté admin
     * @return Response
     * @Route("/admin/productslist", name="app_products")
     */
    public function listProducts()
    {
        $products = $this->productsRepo->findAll();

        return $this->render('products/list.html.twig', ['products' => $products]);
    }

    /**
     * Ajouter un nouveau produit
     * @param Request $request
     * @param ManagerRegistry $manager
     * @param int $id
     * @return Response
     * @Route("/admin/addproduct/{id}", name="add_product", requirements={"id": "\d+"}, methods={"POST", "GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function addProduct (Request $request, ManagerRegistry $manager, int $id = 0)
    {
        $product = $id > 0 ? $this->productsRepo->find($id) : new Products();

        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $em = $manager->getManager();
            $em->persist($product);
            $em->flush();

            $this->addFlash('success', 'Bravo ' . $product->getLabel() . ' est bien enregistré !');
            return $this->redirectToRoute('app_products');
        }
        else {
            return $this->render('products/editProduct.html.twig', ['form' => $form->createView()]);
        }
    }

    /**
     * Supprimer un produit
     * @param Request $request
     * @param ManagerRegistry $manager
     * @param int $id
     * @return Response
     * @Route("/admin/deleteProduct/{id}", name="delProduct", requirements={"id": "\d+"})
     */
    public function deleteProduct(Request $request, ManagerRegistry $manager, int $id)
    {
        if($this->isCsrfTokenValid('delete'.$id, $request->get('_token')))
        {
            $product = $this->productsRepo->find($id);
            $em = $manager->getManager();
            $em->remove($product);
            $em->flush();

            $this->addFlash('success', 'Bravo ' . $product->getLabel() . ' a bien été supprimé :D');
            return $this->redirectToRoute('app_products');
        }
        else
        {
            return new Response("<h1>C'est pas bien !!!</h1>");
        }
    }

    /**
     * Détail d'un produit en accès public
     * @param $id
     * @return Response
     * @Route("/productDetails/{id}", name="product_details", requirements={"id": "\d+"})
     */
    public function details($id)
    {
        $product = $this->productsRepo->find($id);
        $mai = $this->dispoRepo->allDatesForOneMonth($id, '2022-05-01', '2022-05-31');
        //dump($mai);
        return $this->render('admin/product_details.html.twig', ['product' => $product, 'mai' => $mai]);
    }

    /**
     * Gestion de la saison (ouverture, fermeture de la période) -> todo:à mettre dans seasonController
     * @param Request $request
     * @param ManagerRegistry $manager
     * @param int $id
     * @return Response
     * @Route("/admin/openSeason/{id}", name="open_season", requirements={"id": "\d+"})
     */
    public function openSeason(Request $request, ManagerRegistry $manager, int $id)
    {
        $current_date = new \DateTime();
        $year = $current_date->format('Y');

        $start = $year . '-05-05';
        $end = $year . '-10-11';
        $is_already_opened = $this->dispoRepo->allDispoForOneProduct($id, $start, $end);


        if(!empty($is_already_opened))
        {
            $this->addFlash('success', 'la saison est déjà ouverte pour ce logement');
            return $this->redirectToRoute('app_products');
        }

        if($this->isCsrfTokenValid('open'.$id, $request->get('_token')))
        {
            $product = $this->productsRepo->find($id);

            $season = $this->dispoRepo->daysBetween2Dates($start, $end);

            foreach ($season as $day)
            {
                $dispo = new Disponibilites();
                $dispo->setDay($day);
                $dispo->setProductId($product);
                $dispo->setIsBooked(false);

                $em = $manager->getManager();
                $em->persist($dispo);
                $em->flush();
            }


            $this->addFlash('success', 'Bravo !');
            return $this->redirectToRoute('app_products');
        }
        else
        {
            return new Response("<h1>C'est pas bien !!!</h1>");
        }
    }
}

templates/products/editProduct.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un produit{% endblock %}

{% block body %}
    <div class="container">

        <h1>Ajouter un produit</h1>

        {{ form_start(form) }}

        <div class="row justify-content-center">
            <div class="col-sm-6">{{ form_row(form.rental_type) }}</div>
        </div>
        <div class="row">
            <div class="col-sm-6">{{ form_row(form.label) }}</div>
            <div class="col-sm-6">{{ form_row(form.description)  }}</div>
        </div>


        {{ form_rest(form) }}
        {{ form_end(form) }}

    </div>

{% endblock %}

templates/products/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits {% endblock %}

{% block body %}
<div class="container">

    <h1>Liste des produits</h1>

{#    <form action="{{ path('delProduct') }}"
          method="post"
          class="ms-2">
        <input type="hidden" name="_token" value="{{ csrf_token('delete'~product.id) }}">
        <button type="submit" class="btn btn-outline-danger btn-sm">
            <i class="fa-solid fa-trash"></i>
        </button>
    </form>#}

    {% for msg in app.flashes('success') %}
        <div class="row d-flex flex-row justify-content-center mb-2">
            <div class="alert alert-success">
                {{ msg }}
            </div>
        </div>
    {% endfor %}


    <table class="table">
        <thead>
            <th scope="col">ID</th>
            <th scope="col">Type</th>
            <th scope="col">Label</th>
            <th scope="col">Propriétaire</th>
            <th scope="col">#</th>

        </thead>

        <tbody>
        {% for product in products %}

            <tr>
                <th scope="row">{{ product.id }}</th>
                <td>{{ product.rentalType.label }}</td>
                <td>{{ product.label }}</td>
                <td>{{ product.ownerId.lastname }}</td>
                <td>
                    <span class="float-end d-flex flex-row justify-content-between">
                        <a href="{{ path("product_details", {id: product.id} ) }}" class="btn btn-outline-primary btn-sm me-2">
                            <i class="fa-solid fa-eye"></i>
                        </a>
                        <a href="{{ path("add_product", {id: product.id} ) }}" class="btn btn-outline-warning btn-sm">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        <form action="{{ path('open_season', {id: product.id}) }}"
                              method="post"
                              onsubmit="return confirm('Êtes-vous sûr de vouloir ouvrir ce logement à la location?')"
                              class="ms-2">
                            <input type="hidden" name="_token" value="{{ csrf_token('open'~product.id) }}">
                            <button type="submit" class="btn btn-outline-success btn-sm">
                                <i class="fa-solid fa-plus"></i>
                            </button>
                        </form>
                        <form action="{{ path('delProduct', {id: product.id}) }}"
                              method="post"
                              onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce produit?')"
                              class="ms-2">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete'~product.id) }}">
                            <button type="submit" class="btn btn-outline-danger btn-sm">
                                <i class="fa-solid fa-trash"></i>
                            </button>
                        </form>
                </span>
                </td>

            </tr>

        {% endfor %}
        </tbody>


    </table>

</div>

{% endblock %}